# Generated by Django 5.2.7 on 2025-11-13 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_remove_reservation_contract_alter_gym_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='contract_text',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='متن قرار داد'),
            preserve_default=False,
        ),
    ]
