# Generated by Django 5.2.7 on 2025-11-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_gym_contract_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='contract',
        ),
        migrations.AddField(
            model_name='reservation',
            name='contract',
            field=models.BooleanField(default=False, verbose_name='وضعیت قرار داد'),
        ),
    ]
