# Generated by Django 5.2.7 on 2025-11-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_remove_gym_contract_reservation_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ref_id',
        ),
    ]
